### ISSUE TITLE
301 Redirect Broken

### ISSUE THREAD

**Issue by cancan101** [4Catalyzer/flask-resty#216]
repost from: https://github.com/4Catalyzer/flask-resty/pull/213#issuecomment-435114839

301 redirects (eg from extra `/`) are broken.

301 code sent however json content is attached (both in debug and not in debug).

This leads to crhome `Resource interpreted as Document but transferred with MIME type application/json: "http://localhost:5000/admin".` and then ignoring the redirect.

Content in debug.
```
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/werkzeug/routing.py", line 1538, in match
    rv = rule.match(path, method)
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/werkzeug/routing.py", line 776, in match
    raise RequestSlash()
werkzeug.routing.RequestSlash

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/werkzeug/routing.py", line 1542, in match
    safe='/:|+') + '/', query_args))
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None
```

**Comment by taion** [comment]
I opened https://github.com/pallets/flask/issues/2984 upstream. Will work around here.
